[package]
name = "essay-ml"
version = "0.1.0"
edition = "2021"
publish=false

[lib]
path = "src/lib.rs"

[dependencies]
env_logger = { version = "0.10.0" }
log = { version = "0.4.17" }
essay-tensor = { path = "crates/essay-tensor" }
essay-opencl = { path = "crates/essay-opencl" }
essay-nn = { path = "crates/essay-nn" }

[workspace]
members = [
    "crates/*",
]

[[bench]]
name = "tensor-add"
harness = false
