[package]
name = "essay-graphics-winit"
version = "0.1.34-dev"
edition = "2021"

[dependencies]
env_logger = { version = "0.11" }
log = { version = "0.4.17" }
essay-graphics-api = { path = "../essay-graphics-api" }
swash = "0.1"
winit = { version = "0.29", features = ["rwh_05"] }
pollster = "0.3"
futures-intrusive = "0.5"
bytemuck = "1.14"
bytemuck_derive = "1.5"

[lib]
doctest = false
