[package]
name = "essay-graphics-api"
version = "0.1.34-dev"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }
essay-tensor = { path = "../../../essay-tensor" }
#essay-tensor = { git = "git://github.com/ferg-essay/essay-tensor", version="0.1.13" }

[lib]
doctest = false
